### ISSUE TITLE
Unable to find ffmpeg binary x86_64

### ISSUE THREAD

**Issue by Royzac** [imageio/imageio-ffmpeg#74]
Hello,

Is there a ffmpeg binary available for this architecture? 

I'm running across what seems to be an executable issue(error below for reference) and it's possible that the ffmpeg binary that I'm using might not be correct. My program is being deployed using a lambda environment with a runtime setting of python3.9 and x86_64 architecture

I tried both the most recent snapshot and release from this link.
[](https://evermeet.cx/ffmpeg/)

Thanks,
Zack

[ERROR] OSError: MoviePy error: failed to read the duration of file /tmp/magic-assets-public-drops---sample-video.mp4.
Here are the file infos returned by ffmpeg:

-i: /var/task/ffmpeg: cannot execute binary file

Traceback (most recent call last):
  File "/var/task/CreateThumbnail.py", line 99, in handler
    create_video_thumbnail(bucket, key, file_name, extension)
  File "/var/task/CreateThumbnail.py", line 72, in create_video_thumbnail
    resize_video(thumb_download_path, thumb_upload_path)
  File "/var/task/CreateThumbnail.py", line 30, in resize_video
    with VideoFileClip(video_path) as video:
  File "/var/task/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/var/task/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "/var/task/moviepy/video/io/ffmpeg_reader.py", line 296, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: failed to read the duration of file %s.\n"

**Comment by almarklein** [comment]
Linux x86_64 should be fine. Could also be a problem with file permission flags (not marked as executable)?
